version: '3.8'
services:
  app:
    build:
      context: .
    container_name: app-server
    volumes:
      - .:/var/www
    ports:
      - "${APP_PORT}:80"
    depends_on:
      - mariadb
      - redis
    restart: unless-stopped
  mariadb:
    image: mariadb:latest
    container_name: mariadb-server
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  mariadb_data:
  redis_data:
