version: '3.8'
services:
  app:
    build:
      context: .
    container_name: app-server
    volumes:
      - .:/var/www
    ports:
      - "${APP_PORT}:80"
    depends_on:
      - redis
    restart: unless-stopped
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  redis_data:
